/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CsvCodeBlockPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

class CsvParseError extends Error {
  constructor(message, row, field, line) {
    super(message);
    this.name = "CsvParseError";
    this.row = row;
    this.field = field;
    this.line = line;
  }
}

class CsvParser {
  constructor(source, delimiter = ',') {
    this.source = source;
    this.delimiter = delimiter;
  }

  forEachRow(onRow) {
    const source = this.source;
    const delimiter = this.delimiter;
    const STATE_FIELD_START = 0;
    const STATE_IN_UNQUOTED = 1;
    const STATE_IN_QUOTED = 2;
    const STATE_AFTER_QUOTE = 3;
    let currentRow = [];
    let currentFieldParts = [];
    let fieldStart = 0;
    let state = STATE_FIELD_START;
    let rowNumber = 1;
    let fieldNumber = 1;
    let lineNumber = 1;
    let lastTokenWasDelimiter = false;

    const appendPendingFieldText = (end) => {
      if (fieldStart < end) {
        currentFieldParts.push(source.slice(fieldStart, end));
      }
    };

    const throwParseError = (message) => {
      throw new CsvParseError(message, rowNumber, fieldNumber, lineNumber);
    };

    const pushField = () => {
      if (currentFieldParts.length === 0) {
        currentRow.push('');
      } else if (currentFieldParts.length === 1) {
        currentRow.push(currentFieldParts[0]);
      } else {
        currentRow.push(currentFieldParts.join(''));
      }
      currentFieldParts = [];
      fieldNumber++;
      lastTokenWasDelimiter = false;
    };

    const pushRow = () => {
      if (state === STATE_FIELD_START && lastTokenWasDelimiter) {
        pushField();
      } else if (state === STATE_IN_UNQUOTED || state === STATE_AFTER_QUOTE) {
        pushField();
      } else if (state === STATE_FIELD_START && currentRow.length === 0) {
        pushField();
      }
      if (currentRow.length > 1 || currentRow[0] !== '') {
        onRow(currentRow, rowNumber);
      }
      currentRow = [];
      rowNumber++;
      fieldNumber = 1;
      state = STATE_FIELD_START;
      lastTokenWasDelimiter = false;
    };

    for (let i = 0; i < source.length; i++) {
      const char = source[i];
      const nextChar = source[i + 1];
      const isNewLine = char === "\n" || char === "\r";

      if (state === STATE_FIELD_START) {
        if (char === delimiter) {
          pushField();
          fieldStart = i + 1;
          lastTokenWasDelimiter = true;
        } else if (isNewLine) {
          pushRow();
          if (char === "\r" && nextChar === "\n") {
            i++;
          }
          fieldStart = i + 1;
          lineNumber++;
        } else if (char === '"') {
          state = STATE_IN_QUOTED;
          fieldStart = i + 1;
        } else {
          state = STATE_IN_UNQUOTED;
          fieldStart = i;
        }
        continue;
      }

      if (state === STATE_IN_UNQUOTED) {
        if (char === delimiter) {
          appendPendingFieldText(i);
          pushField();
          fieldStart = i + 1;
          state = STATE_FIELD_START;
          lastTokenWasDelimiter = true;
        } else if (isNewLine) {
          appendPendingFieldText(i);
          pushRow();
          if (char === "\r" && nextChar === "\n") {
            i++;
          }
          fieldStart = i + 1;
          lineNumber++;
        } else if (char === '"') {
          throwParseError("Unexpected quote inside an unquoted field");
        }
        continue;
      }

      if (state === STATE_IN_QUOTED) {
        if (char === '"') {
          appendPendingFieldText(i);
          if (nextChar === '"') {
            currentFieldParts.push('"');
            i++;
            fieldStart = i + 1;
          } else {
            state = STATE_AFTER_QUOTE;
            fieldStart = i + 1;
          }
        } else if (char === "\r") {
          if (nextChar === "\n") {
            i++;
          }
          lineNumber++;
        } else if (char === "\n") {
          lineNumber++;
        }
        continue;
      }

      if (char === delimiter) {
        pushField();
        fieldStart = i + 1;
        state = STATE_FIELD_START;
        lastTokenWasDelimiter = true;
      } else if (isNewLine) {
        pushRow();
        if (char === "\r" && nextChar === "\n") {
          i++;
        }
        fieldStart = i + 1;
        lineNumber++;
      } else if (char === " " || char === "\t") {
        fieldStart = i + 1;
      } else {
        throwParseError(`Unexpected character "${char}" after a closing quote`);
      }
    }

    if (state === STATE_IN_QUOTED) {
      throwParseError("Unclosed quoted field");
    }

    if (state === STATE_IN_UNQUOTED) {
      appendPendingFieldText(source.length);
      pushField();
      state = STATE_FIELD_START;
    } else if (state === STATE_AFTER_QUOTE) {
      pushField();
      state = STATE_FIELD_START;
    } else if (state === STATE_FIELD_START && lastTokenWasDelimiter) {
      pushField();
    }

    if (currentRow.length > 0) {
      pushRow();
    }
  }

}

function detectCsvDelimiter(source) {
  const candidates = [",", ";"];
  const scores = new Map(candidates.map((delimiter) => [delimiter, 0]));
  const matches = new Map(candidates.map((delimiter) => [delimiter, 0]));
  let inQuotes = false;
  let rowCounts = new Map(candidates.map((delimiter) => [delimiter, 0]));
  let sampledRows = 0;
  let sawRowData = false;

  const commitRow = () => {
    if (!sawRowData) {
      rowCounts = new Map(candidates.map((delimiter) => [delimiter, 0]));
      return;
    }
    sampledRows++;
    for (const delimiter of candidates) {
      const count = rowCounts.get(delimiter);
      if (count > 0) {
        scores.set(delimiter, scores.get(delimiter) + count);
        matches.set(delimiter, matches.get(delimiter) + 1);
      }
    }
    rowCounts = new Map(candidates.map((delimiter) => [delimiter, 0]));
    sawRowData = false;
  };

  for (let i = 0; i < source.length && sampledRows < 10; i++) {
    const char = source[i];
    const nextChar = source[i + 1];

    if (char === '"') {
      if (inQuotes && nextChar === '"') {
        i++;
      } else {
        inQuotes = !inQuotes;
      }
      sawRowData = true;
      continue;
    }

    if (!inQuotes && (char === "\n" || char === "\r")) {
      if (char === "\r" && nextChar === "\n") {
        i++;
      }
      commitRow();
      continue;
    }

    if (!inQuotes && scores.has(char)) {
      rowCounts.set(char, rowCounts.get(char) + 1);
      sawRowData = true;
    } else if (char.trim().length > 0) {
      sawRowData = true;
    }
  }

  commitRow();

  if (scores.get(";") > scores.get(",") && matches.get(";") >= matches.get(",")) {
    return ";";
  }
  return ",";
}

function createCellContent(doc, cell, text) {
  const trimmed = text.trim();
  if (trimmed.length > 0) {
    try {
      const url = new URL(trimmed);
      if (url.protocol === "http:" || url.protocol === "https:" || url.protocol === "mailto:") {
        const link = doc.createElement("a");
        link.className = "csv-codeblock__link";
        link.href = trimmed;
        link.textContent = text;
        if (url.protocol !== "mailto:") {
          link.target = "_blank";
          link.rel = "noopener noreferrer";
        }
        cell.appendChild(link);
        return;
      }
    } catch (error) {
    }
  }
  cell.textContent = text;
}


class CsvCodeBlockPlugin extends import_obsidian.Plugin {
  async onload() {
    // Register CSV code block processor
    this.registerMarkdownCodeBlockProcessor("csv", (source, el, ctx) => {
      this.renderTable(source, el, "auto");
    });

    // Register TSV code block processor
    this.registerMarkdownCodeBlockProcessor("tsv", (source, el, ctx) => {
      this.renderTable(source, el, "\t");
    });
  }

  renderTable(source, el, delimiter) {
    const resolvedDelimiter = delimiter === "auto" ? detectCsvDelimiter(source) : delimiter;
    const doc = el.ownerDocument;
    const wrapper = doc.createElement("div");
    const scrollContainer = doc.createElement("div");
    const table = doc.createElement("table");
    const head = doc.createElement("thead");
    const body = doc.createElement("tbody");
    let expectedColumnCount = 0;
    let isHeaderRow = true;

    wrapper.className = "csv-codeblock csv-codeblock--compact csv-codeblock--zebra";
    scrollContainer.className = "csv-codeblock__scroll";
    table.className = "csv-codeblock__table";

    try {
      const parser = new CsvParser(source, resolvedDelimiter);

      parser.forEachRow((rowData, rowNumber) => {
        if (expectedColumnCount === 0) {
          expectedColumnCount = rowData.length;
        } else if (rowData.length !== expectedColumnCount) {
          throw new CsvParseError(
            `Row has ${rowData.length} fields, expected ${expectedColumnCount}`,
            rowNumber,
            rowData.length + 1,
            rowNumber
          );
        }
        const row = doc.createElement("tr");
        const cellTag = isHeaderRow ? "th" : "td";
        for (let i = 0; i < rowData.length; i++) {
          const cell = doc.createElement(cellTag);
          createCellContent(doc, cell, rowData[i]);
          if (isHeaderRow) {
            cell.scope = "col";
          }
          row.appendChild(cell);
        }
        if (isHeaderRow) {
          row.className = "csv-codeblock__header-row";
          head.appendChild(row);
          isHeaderRow = false;
        } else {
          body.appendChild(row);
        }
      });
    } catch (error) {
      this.renderError(el, doc, error);
      return;
    }

    if (head.childNodes.length > 0) {
      table.appendChild(head);
    }
    table.appendChild(body);
    wrapper.appendChild(scrollContainer);
    scrollContainer.appendChild(table);
    el.appendChild(wrapper);
  }

  renderError(el, doc, error) {
    const wrapper = doc.createElement("div");
    const title = doc.createElement("div");
    const details = doc.createElement("div");

    wrapper.className = "csv-codeblock csv-codeblock--error";
    title.className = "csv-codeblock__error-title";
    details.className = "csv-codeblock__error-details";
    title.textContent = "Malformed CSV";

    if (error instanceof CsvParseError) {
      details.textContent = `Row ${error.row}, field ${error.field} (line ${error.line}): ${error.message}.`;
    } else if (error instanceof Error) {
      details.textContent = error.message;
    } else {
      details.textContent = String(error);
    }

    wrapper.appendChild(title);
    wrapper.appendChild(details);
    el.appendChild(wrapper);
  }
}
