/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CsvCodeBlockPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

class CsvParser {
  constructor(source, delimiter = ',') {
    this.source = source;
    this.delimiter = delimiter;
  }

  parse() {
    const rows = [];
    let currentRow = [];
    let currentField = '';
    let inQuotes = false;

    const pushField = () => {
      currentRow.push(currentField);
      currentField = '';
    };

    const pushRow = () => {
      pushField();
      if (currentRow.length > 1 || currentRow[0] !== '') {
        rows.push(currentRow);
      }
      currentRow = [];
    };

    for (let i = 0; i < this.source.length; i++) {
      const char = this.source[i];
      const nextChar = this.source[i + 1];

      if (char === '"') {
        if (inQuotes && nextChar === '"') {
          currentField += '"';
          i++;
        } else {
          inQuotes = !inQuotes;
        }
      } else if (char === this.delimiter && !inQuotes) {
        pushField();
      } else if ((char === '\n' || char === '\r') && !inQuotes) {
        if (char === '\r' && nextChar === '\n') {
          i++;
        }
        pushRow();
      } else {
        currentField += char;
      }
    }

    if (currentField.length > 0 || currentRow.length > 0) {
      pushRow();
    }

    return rows;
  }
}


class CsvCodeBlockPlugin extends import_obsidian.Plugin {
  async onload() {
    // Register CSV code block processor
    this.registerMarkdownCodeBlockProcessor("csv", (source, el, ctx) => {
      this.renderTable(source, el, ",");
    });

    // Register TSV code block processor
    this.registerMarkdownCodeBlockProcessor("tsv", (source, el, ctx) => {
      this.renderTable(source, el, "\t");
    });
  }

  renderTable(source, el, delimiter) {
    const parser = new CsvParser(source, delimiter);
    const data = parser.parse();

    const table = el.createEl("table");
    const body = table.createEl("tbody");

    data.forEach(rowData => {
      const row = body.createEl("tr");
      rowData.forEach(field => {
        row.createEl("td", { text: field });
      });
    });
  }
}
