/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CsvCodeBlockPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

class CsvParser {
  constructor(source, delimiter = ',') {
    this.source = source;
    this.delimiter = delimiter;
  }

  forEachRow(onRow) {
    const source = this.source;
    const delimiter = this.delimiter;
    let currentRow = [];
    let currentFieldParts = [];
    let fieldStart = 0;
    let inQuotes = false;

    const appendPendingFieldText = (end) => {
      if (fieldStart < end) {
        currentFieldParts.push(source.slice(fieldStart, end));
      }
    };

    const pushField = () => {
      if (currentFieldParts.length === 0) {
        currentRow.push('');
      } else if (currentFieldParts.length === 1) {
        currentRow.push(currentFieldParts[0]);
      } else {
        currentRow.push(currentFieldParts.join(''));
      }
      currentFieldParts = [];
    };

    const pushRow = () => {
      pushField();
      if (currentRow.length > 1 || currentRow[0] !== '') {
        onRow(currentRow);
      }
      currentRow = [];
    };

    for (let i = 0; i < source.length; i++) {
      const char = source[i];
      const nextChar = source[i + 1];

      if (char === '"') {
        if (inQuotes && nextChar === '"') {
          appendPendingFieldText(i);
          currentFieldParts.push('"');
          i++;
          fieldStart = i + 1;
        } else {
          appendPendingFieldText(i);
          inQuotes = !inQuotes;
          fieldStart = i + 1;
        }
      } else if (char === delimiter && !inQuotes) {
        appendPendingFieldText(i);
        pushField();
        fieldStart = i + 1;
      } else if ((char === '\n' || char === '\r') && !inQuotes) {
        appendPendingFieldText(i);
        if (char === '\r' && nextChar === '\n') {
          i++;
        }
        pushRow();
        fieldStart = i + 1;
      }
    }

    appendPendingFieldText(source.length);
    if (currentFieldParts.length > 0 || currentRow.length > 0) {
      pushRow();
    }
  }

  parse() {
    const rows = [];
    this.forEachRow((row) => rows.push(row));
    return rows;
  }
}


class CsvCodeBlockPlugin extends import_obsidian.Plugin {
  async onload() {
    // Register CSV code block processor
    this.registerMarkdownCodeBlockProcessor("csv", (source, el, ctx) => {
      this.renderTable(source, el, ",");
    });

    // Register TSV code block processor
    this.registerMarkdownCodeBlockProcessor("tsv", (source, el, ctx) => {
      this.renderTable(source, el, "\t");
    });
  }

  renderTable(source, el, delimiter) {
    const parser = new CsvParser(source, delimiter);
    const doc = el.ownerDocument;
    const wrapper = doc.createElement("div");
    const scrollContainer = doc.createElement("div");
    const table = doc.createElement("table");
    const body = doc.createElement("tbody");

    wrapper.className = "csv-codeblock";
    scrollContainer.className = "csv-codeblock__scroll";
    table.className = "csv-codeblock__table";

    parser.forEachRow((rowData) => {
      const row = doc.createElement("tr");
      for (let i = 0; i < rowData.length; i++) {
        const cell = doc.createElement("td");
        cell.textContent = rowData[i];
        row.appendChild(cell);
      }
      body.appendChild(row);
    });

    table.appendChild(body);
    wrapper.appendChild(scrollContainer);
    scrollContainer.appendChild(table);
    el.appendChild(wrapper);
  }
}
